### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by sn0n** [esteemapp/esteem-mobile#382]
The app seems much slower without some sort of loading indicator. Staring at an app with literally nothing indicating progress of a request seems to be alone to watching a pot of water boil. Impatience kicks in and I'm clicking 5 things looking for something to load... Only to have all 5 actions click in finally... This is using the latest beta on play store with the new interface. Steem user is @sn0n also.

**Comment by feruzm** [comment]
Thank you @sn0n !

Could you please share some details (include screenshot if possible):
1. if you logged in with steem connect or without
2. what android version you have, what is device name
3. what pages and what action causes slowness, does restart of app help

**Comment by horpeyloaded** [comment]
This is true cuz sometimes I encounter similar issue.

App becomes slow and stuck on splash for longer time, I had to quit and relaunch several times before I could login successfully.

I think this is because the **Splash** and **Pin** use internet connection to load up. Sometimes the app shows me to create new pin probably because of my slow internet connection. 

IMO, first, the splash should be removed after the first launch and shouldn't be used to run dependencies as I have requested. 

Secondly, the PIN should load from Cache memory `offline memory` so user can still enter the app if the enter correct. The app can then quick run the dependencies on the feed panel.

This will give user best experience surfing with the app. 
~ Just my thought 💭 😶
