### ISSUE TITLE
Remove top post card padding

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-mobile#401]
Android version of app have unnecessary free space on top of each card which is making first card to add a bit more space to the top filter area and it looks misaligned: 
![2019-01-11-12 44 10](https://user-images.githubusercontent.com/32987666/51029943-f0ca7580-15a8-11e9-9432-f794668ed5c8.jpg)

So if we just remove that top free space and make bottom space twice bigger will it fix the issue?

![2](https://user-images.githubusercontent.com/32987666/51030075-5ae31a80-15a9-11e9-9354-f2e5521860b0.jpg)

**Comment by ue** [comment]
![screen shot 2019-01-14 at 12 20 41](https://user-images.githubusercontent.com/9980498/51104324-eb626a80-17f6-11e9-988d-875f8f67f070.png)
![screen shot 2019-01-14 at 12 20 49](https://user-images.githubusercontent.com/9980498/51104326-eb626a80-17f6-11e9-8453-e239efb107e5.png)

as I told before this space necessary thing. because we are using shadow for the card. for this styles its need to be use this space other wise it will look as the second picture. 

what is your decision? shadow or spaces? @fildunsky

**Comment by fildunsky** [comment]
We need both :) I can see other apps are implementing this without any issue. There has to be way to do it...

**Comment by feruzm** [comment]
I think, all you have to do is to move card up same pixels as height of shadow

**Comment by ue** [comment]
if I do that it will crush each other. when user scroll this bar goes disappear (z-index)
