### ISSUE TITLE
Using capital letter Tag crashes app

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#423]
The app should warn users when capital letter is used in Tags; `Use only lowercase letters` and grey out the `Publish button` until user's fix the tag to avoid crash.

**Comment by feruzm** [comment]
or always do auto lowercase when user submitting post.

**Comment by tobias-g1** [comment]
I think the issue mentioned here:

https://steemit.com/utopian-io/@horpey/esteem-mobile-v2-using-capital-letter-tag-crashes-app

is actually due to a permlink being duplicated rather than the tags, if you see the following you can see a post that was created using the application that has uppercase tags:

https://busy.org/@votezilla/testing6786567d
