### ISSUE TITLE
[BUG] Steemconnect Login Error - Username with a Dot in the Name

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#463]
**Describe the bug**
If you try to log in with Steemconnect in the current version of the app on an Android device, there is an error. This error occurs e.g. when logging in with a username that has a dot in the username. An account that does not contain any special characters or dots, because the login works.

**To Reproduce**
1. install the latest version (2.0.6) for Android on your phone

2. go to the login area

3. switch to login with SteemConnect 

4. try to log in with a user account that contains a point.

5. the login should fail and the following error message appears: Error: auth.invalid_credentials

**Expected behavior**

Normally, the login should work. This I have also tested with another account without a dot in the name. I expected the login to work with SteemConnect.

**Screenshots or Video**

![ezgif-4-3ea12508ae69](https://user-images.githubusercontent.com/35930080/51397679-04925080-1b42-11e9-862b-d4a76a6113f4.gif)

![screenshot_20190118_172413_app esteem mobile](https://user-images.githubusercontent.com/35930080/51399339-00683200-1b46-11e9-85b9-7b6c6d0c50e9.png)

![screenshot_20190118_172548_app esteem mobile](https://user-images.githubusercontent.com/35930080/51399420-33122a80-1b46-11e9-90e9-77b5705ae36a.png)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Pro
 - OS: Latest Android (9)
 - Version 2.0.6

**Additional context**
U need an Steemit Account with Active Key and a Username with a dot in the Name

**Comment by feruzm** [comment]
@louis88-steemit after several attempts to reproduce this, we think this issue isn't coming from eSteem mobile, most likely reason because steem connect credentials changed since this user was added into steem connect login screen. Can you try, removing account from login screen After you click Steemconnect and then Continue button you see Choose an account, from there delete account and re-login into steem connect again to see if it works?
