### ISSUE TITLE
Markdown parsing link issue

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#517]
![](https://cdn.discordapp.com/attachments/487610005558657034/539355503378169856/image.png)

**Comment by ue** [comment]
in that case the data coming as `@steemhunt` and our mark down parser function handle that and changed a clickable link for open inside the application so its turn to to `<a href link` we have to do that otherwise app can not open that. and its has two code quote (``) thats why its doing render as are I have no idea right now. I have to research that leave them for no :(
