### ISSUE TITLE
Let's confirm before closing issues for better tracking

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#557]
Please let's verify if a feature is properly implemented or a bug is fixed after release before closing the issue.

Users stop using app as soon as they still see bugs that were told it would be fixed in the upcoming version. Or better test it and verify it very well before the release and closing the issue. Users don’t care about backend, they only want to use simple and perfect app (no-one cares about the code but the product)

A user told me
> If eSteem is not capable of making a perfect mobile app then let's stick to Surfer.

I'm getting depressed of users' comment in my inbox about this mobile app. Check eSteem channel and see some people leaving to use other app. eSteem needs perfect mobile app to maintain its stands. It seems no one wants to hear it's still in Beta mode anymore.

**Comment by feruzm** [comment]
@horpeyloaded Thanks for bringing this up! Please make sure users feedback is about v2 not legacy version. We will soon announce the deprecation of v1 or legacy app and production release of v2. That way there won't be any confusion about feedbacks. Majority of feedback/complain I receive is either about v1 or not using up to date version of v2.

As for issue tracking, I will ask team to provide test version for issue creators to test and close their own issues, instead of developer closing issues.

**Comment by horpeyloaded** [comment]
The feedbacks are for v2 not 1.0.6 @feruzm

**Comment by feruzm** [comment]
We will change how we handle reported issues, as I mentioned. But it will add extra overhead/take some time from devs which we could focus on development, however it is important that user’s feedback is properly followed up. I have proposed better approach for team. We will give it a try and see how it goes

**Comment by horpeyloaded** [comment]
Thanks for your consideration @feruzm
