### ISSUE TITLE
[esteem mobile v2 iOS] Double voting of comments

### ISSUE THREAD

**Issue by quekery** [esteemapp/esteem-mobile#642]
Comments shows the value 0.000 STU and the voters are not showed.

I was able to double upvote the same comment. First I voted a comment with Partiko. Second I voted the same comment with a different upvote value (lower). My vote was replaced with the lower upvote value and it was added a second upvote from the user @mys. I tried this 3 times and the result was always the same.

**Comment by feruzm** [comment]
Hey @quekery, it is expected behavior on Steem. You can always replace your vote with different percentage but each post I think has limit of 5 or 3 times vote changing limit. But overwriting existing vote with other value is completely ok and possible. You should however receive error when you try to vote with same percent. Other issue about payout not showing we could check but if your vote doesn't have value more than let's say 0.001 then it is not visible which is ok too from UI perspective.
